name_model = "10B"
project = "debug_10B_zero_band"

[train]
micro_bs = 2
ac_ckpt = true
sharding_strategy = "SHARD_GRAD_OP"

[optim]
batch_size = 1024 #2M tokens bs
warmup_steps = 1000
total_steps = 88_000
lr = 3e-4

[data]
seq_length = 8192
