name_model = "10B"
project = "10B_zero_band"

[train]
micro_bs = 1
ac_ckpt = true

[optim]
sched_type = "wsd-sqrt"
batch_size = 128 #1M tokens bs
warmup_steps = 1000
total_steps = 1_000_000_000_000
lr = 7.5e-5

adam_betas1 = 0.9
adam_betas2 = 0.95
weight_decay = 0.1

z_loss = true

[data]
seq_length = 8192
dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
dataset_ratio = "55:10:20:10:5"
num_workers = 8

[diloco]
inner_steps = 100
compression = "uint8"

[ckpt]
interval = 100
topk = 40
live_recovery = true
path = "outputs_10B_zero_band"
# remote_data_path = "gs://checkpoints_pi/10b_data/"
