[project]
name = "zeroband"
version = "0.1.0"
description = "ZeroBand is a production ready codebase for decentralized training of LLM"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.4.1",
    "numpy",
    "setuptools",
    "transformers>=4.44.2",
    "datasets>=3.0.0",
    "pydantic_config @ git+https://github.com/samsja/pydantic_config.git@e529c9c",
    "einops",
    "torchdata>=0.8.0",
    "fsspec[gcs]>=2024.3.1",
    "ninja",
    "zstandard",
    "pyarrow",
    "psutil",
]

[project.optional-dependencies]
all = [
    "wandb",
    "asyncio>=3.4.3",
    "aiohttp>=3.10.5",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true # allow direct references to git repos in dependencies

[tool.ruff]
line-length = 120

[tool.uv]
dev-dependencies = ["ruff>=0.5.0", "pre-commit>=3.0.0","pytest>=7.0.0", "faker"]
