name_model = "150M"
project = "debug_150m_zero_band"

[train]
micro_bs = 64 # change this base on the gpu
reshard_after_forward = false

[optim]
batch_size = 512
warmup_steps = 1000
total_steps = 88_000

[optim.optim]
lr = 4e-4

