name_model = "150M"
project = "debug_150m_zero_band"

[train]
micro_bs = 16 # change this base on the gpu
reshard_after_forward = false

[optim]
batch_size = 512
warmup_steps = 500
total_steps = 8192


[optim.optim]
lr = 4e-4
