name_model = "150M"
project = "debug_150m_zero_band"
type_model = "llama2"

[train]
micro_bs = 16 # change this base on the gpu
reshard_after_forward = true

[optim]
batch_size = 512
warmup_steps = 1000
total_steps = 88_000
lr = 4e-4


[data]
dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/StackV1-popular"
dataset_ratio = "80:20"
num_workers = 2