name_model = "150M"
project = "debug_150m_zero_band"
type_model = "llama2"

[train]
micro_bs = 64 # change this base on the gpu

[optim]
batch_size = 512
warmup_steps = 1000
total_steps = 88_000
lr = 4e-4