name: Tests on GPU

on:
  push:
    branches:
      - main
  pull_request:
    # This will trigger the workflow for pull requests to any branch
    types: [opened, synchronize, reopened]

jobs:
  gpu-tests:
    name: python
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Set up Python 
        run: uv python install 3.10.13

      - name: Install the project
        run: uv sync
      
      - name: Install flash-attn
        run: uv sync --extra fa

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: uv run pytest tests